name: GBCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: gbo

    steps:
      - name: Disable SSL verification (temporary)
        run: git config --global http.sslVerify false

      - uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bottest-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bottest-

      - name: Install Rust
        uses: msrd0/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run build
        run: |
          cargo build --locked

      - name: Run unit tests
        run: |
          cargo test --locked

      - name: Run integration tests
        run: |
          cargo test --locked --features integration

      - name: Run all tests with full features
        run: |
          cargo test --locked --features full
